name: Build and deploy container app to Azure Web App - zu-bbbearbeiten-stateless

on:
  push:
    tags:
      - 'v*'  # Reagiert auf Tags, die mit "v" beginnen, z.B. v1.0.0, v2.0.0
  workflow_dispatch:

jobs:
  test:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest
      run: |
        pytest --maxfail=1 --disable-warnings -q

  build:
    runs-on: 'ubuntu-latest'
    needs: test  # Der Build-Prozess startet nur, wenn die Tests erfolgreich sind

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_e4131c6103a64858a67298b4348ed9fb }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d06153b75cba4017afd8ba81a5d8e93a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_e4131c6103a64858a67298b4348ed9fb }}/appsvc/staticsite:${{ github.ref }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'zu-bbbearbeiten-stateless'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5c3a8865b88045109baaf9e5cee3d878 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_e4131c6103a64858a67298b4348ed9fb }}/appsvc/staticsite:${{ github.ref }}'
